"""
Pandas Fundamentals - Learning Unit 4.22
Creating Pandas Series from Lists and Arrays

This module demonstrates:
1. Understanding Pandas Series
2. Creating a Series from Python Lists
3. Creating a Series from NumPy Arrays
4. Understanding Index and Values
5. Simple Series Operations

Author: Trivin Insight Engine
Date: March 5, 2026
"""

import numpy as np
import pandas as pd


def section_header(title):
    """Print a formatted section header"""
    print("\n" + "=" * 70)
    print(f"  {title}")
    print("=" * 70)


# ============================================================================
# 1. UNDERSTANDING PANDAS SERIES
# ============================================================================

def demonstrate_series_concept():
    """Demonstrate what a Pandas Series is"""
    section_header("1. Understanding Pandas Series")

    satisfaction_scores = pd.Series([4.2, 3.8, 4.5, 4.0])

    print("A Series is one-dimensional labeled data.")
    print("\nExample Series:")
    print(satisfaction_scores)

    print("\nConcept check:")
    print(f"  Type: {type(satisfaction_scores)}")
    print(f"  Default index: {list(satisfaction_scores.index)}")
    print(f"  Values: {list(satisfaction_scores.values)}")

    comparison_array = np.array([4.2, 3.8, 4.5, 4.0])
    print("\nSeries vs NumPy array:")
    print(f"  NumPy type: {type(comparison_array)}")
    print("  NumPy has values but no label index like Series.")


# ============================================================================
# 2. CREATING A SERIES FROM PYTHON LISTS
# ============================================================================

def demonstrate_series_from_list():
    """Create and inspect Series built from Python lists"""
    section_header("2. Creating a Series from Python Lists")

    departments = ["Engineering", "Sales", "Marketing", "HR"]
    department_series = pd.Series(departments)

    print("Series created from list:")
    print(department_series)

    print("\nAutomatic index generated by Pandas:")
    print(department_series.index)

    print("\nSimple access examples:")
    print(f"  Position 0: {department_series[0]}")
    print(f"  Position 2: {department_series[2]}")

    employee_counts = [24, 18, 11, 7]
    employee_count_series = pd.Series(employee_counts)

    print("\nNumeric list to Series:")
    print(employee_count_series)


# ============================================================================
# 3. CREATING A SERIES FROM NUMPY ARRAYS
# ============================================================================

def demonstrate_series_from_numpy_array():
    """Create and inspect Series built from NumPy arrays"""
    section_header("3. Creating a Series from NumPy Arrays")

    response_time_array = np.array([2.1, 1.8, 2.6, 1.9, 2.2], dtype=np.float64)
    response_time_series = pd.Series(response_time_array)

    print("NumPy array:")
    print(response_time_array)
    print(f"Array dtype: {response_time_array.dtype}")

    print("\nSeries from NumPy array:")
    print(response_time_series)
    print(f"Series dtype: {response_time_series.dtype}")

    print("\nData type is preserved when converting array -> Series.")

    print("\nWhy labels matter:")
    labeled_series = pd.Series(
        response_time_array,
        index=["Mon", "Tue", "Wed", "Thu", "Fri"],
    )
    print(labeled_series)


# ============================================================================
# 4. UNDERSTANDING INDEX AND VALUES
# ============================================================================

def demonstrate_index_and_values():
    """Inspect Series index and values with position and label access"""
    section_header("4. Understanding Index and Values")

    productivity_series = pd.Series(
        [88, 91, 84, 95],
        index=["Alice", "Bob", "Charlie", "Diana"],
    )

    print("Series with custom labels:")
    print(productivity_series)

    print("\nInspect components:")
    print(f"  Index: {list(productivity_series.index)}")
    print(f"  Values: {list(productivity_series.values)}")

    print("\nPositional vs label access:")
    print(f"  Positional access (iloc[1]): {productivity_series.iloc[1]}")
    print(f"  Label access (loc['Bob']): {productivity_series.loc['Bob']}")

    print("\nSimple label-aware behavior:")
    bonus_points = pd.Series([2, 1, 3, 2], index=["Alice", "Bob", "Charlie", "Diana"])
    updated_scores = productivity_series + bonus_points
    print(updated_scores)


# ============================================================================
# 5. SIMPLE SERIES OPERATIONS
# ============================================================================

def demonstrate_simple_operations():
    """Perform basic Series operations expected for this milestone"""
    section_header("5. Simple Series Operations")

    monthly_sales = pd.Series([120, 135, 128, 142], index=["Jan", "Feb", "Mar", "Apr"])

    print("Monthly sales Series:")
    print(monthly_sales)

    print("\nBasic operations:")
    print(f"  Mean: {monthly_sales.mean():.2f}")
    print(f"  Max: {monthly_sales.max()}")
    print(f"  Min: {monthly_sales.min()}")

    increased_sales = monthly_sales + 10
    print("\nAfter adding 10 to each month:")
    print(increased_sales)


# ============================================================================
# MAIN EXECUTION
# ============================================================================

def main():
    """Main function to run all Series demonstrations"""
    print("\n")
    print("*" * 70)
    print("*" + " " * 68 + "*")
    print("*  LEARNING UNIT 4.22: PANDAS SERIES FUNDAMENTALS             *")
    print("*  Creating Series from Lists and NumPy Arrays                *")
    print("*" + " " * 68 + "*")
    print("*" * 70)

    demonstrate_series_concept()
    demonstrate_series_from_list()
    demonstrate_series_from_numpy_array()
    demonstrate_index_and_values()
    demonstrate_simple_operations()

    section_header("Summary and Key Takeaways")
    print("""
    ✓ A Pandas Series is 1D labeled data
    ✓ You can create Series from Python lists
    ✓ You can create Series from NumPy arrays
    ✓ Series keeps data values and index labels together
    ✓ Labels add meaning and enable label-aware access
    ✓ Series is a foundation for working with DataFrames later

    Keep examples small and clear while learning core structure.
    """)

    print("\n" + "=" * 70)
    print("  Demonstration Complete!")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    main()
